project:
  type: book

book:
  title: "Operating Systems and Networs SoSe 25 Solutions"
  author: "Igor Dimitrov"
  date: "12/18/2024"
  chapters:
    - index.qmd
    - sh01/01.qmd
    - sh02/02.qmd
    - sh03/03.qmd
    - sh04/04.qmd
    - sh05/05.qmd
    - sh06/06.qmd
    - sh07/07.qmd
    - sh08/08.qmd
    - sh10/10.qmd
  downloads: ["pdf"]
  page-navigation: true

number-depth: 1

bibliography: references.bib

csl: nature.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    number-depth: 1



